<div class="w-full bg-blue-900 text-white border-b-2 border-black">
    <nav class="mx-auto max-w-2xl flex">
        <div class="flex-grow p-3">
            <a class="uppercase text-xl md:text-xl hover:underline hover:text-purple-500 font-bold" href="/">Melty Colors</a>
        </div>
        <a class="text-xl uppercase md:text-xl hover:underline hover:text-purple-500 font-bold py-3 px-4" href="/colors">Browse</a>
        <a class="text-xl uppercase md:text-xl hover:underline hover:text-purple-500 font-bold py-3 px-4" href="/submit">Submit</a>
    </nav>
</div>